#compile a simple thread program
BASE_DIR = ../..

include $(BASE_DIR)/common.mk

OBJS = thread1.o

BIN = demo_thread
CFLGAS += -Wno-unused -Wno-write-strings

all:$(BIN)

include $(BASE_DIR)/rules.mk
