#compile a simple thread program
BASE_DIR = ../..

include $(BASE_DIR)/common.mk

OBJS = thread4.o

BIN = demo_thread4
CFLGAS += -Wno-unused -Wno-write-strings

all:$(BIN)

include $(BASE_DIR)/rules.mk

