#compile a simple thread program
BASE_DIR = ../..

include $(BASE_DIR)/common.mk

OBJS = thread2.o

BIN = demo_thread2
CFLGAS += -Wno-unused -Wno-write-strings

all:$(BIN)

include $(BASE_DIR)/rules.mk

