#compile a simple thread program
BASE_DIR = ../..

include $(BASE_DIR)/common.mk

OBJS = thread3.o

BIN = demo_thread3
CFLGAS += -Wno-unused -Wno-write-strings

all:$(BIN)

include $(BASE_DIR)/rules.mk
